In [2]:
import nltk,os
nltk.download('gutenberg')

from nltk.corpus import gutenberg
import pandas as pd

data=gutenberg.raw('shakespeare-hamlet.txt')

os.makedirs('data',exist_ok=True)

with open('data/hamlet.txt','w') as file:
    file.write(data)

[nltk_data] Downloading package gutenberg to C:\Users\Rishad
[nltk_data]     R\AppData\Roaming\nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


In [3]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

In [5]:
with open('data/hamlet.txt','r') as file:
    text=file.read().lower()
    
tokenizer=Tokenizer()
tokenizer.fit_on_texts([text])
total_words=len(tokenizer.word_index)+1
print(total_words)

4818


In [ ]:
tokenizer.word_index

In [7]:
inputsequences=[]

for line in text.split('\n'):
    token_list=tokenizer.texts_to_sequences([line])[0]
    for i in range(1,len(token_list)):
        n_gram_sequences=token_list[:i+1]
        inputsequences.append(n_gram_sequences)

In [ ]:
inputsequences

In [9]:
max_len=max([len(x) for x in inputsequences])
max_len

14

In [10]:
input_sequences=np.array(pad_sequences(inputsequences,maxlen=max_len,padding='pre'))
input_sequences

array([[   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       [   0,    0,    0, ...,  687,    4,   45],
       ...,
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4],
       [   0,    0,    0, ..., 1047,    4,  193]])

In [12]:
x,y=input_sequences[:,:-1],input_sequences[:,-1]
import tensorflow as tf

y=tf.keras.utils.to_categorical(y,num_classes=total_words)

In [13]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [14]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [15]:
x_train

array([[  0,   0,   0, ...,   0,   0,  78],
       [  0,   0,   0, ...,   2,  95, 550],
       [  0,   0,   0, ..., 536,  63,  44],
       ...,
       [  0,   0,   0, ..., 336,   6,   3],
       [  0,   0,   0, ...,  14,  50,  21],
       [  0,   0,   0, ...,   0,  57, 407]])